import org.junit.Assert;
import org.junit.Test;

import java.util.Collection;
import java.util.List;
import java.util.Map;

import static org.junit.Assert.*;

public class DnaNucleotidesCounterTest {

    @Test
    public void countSmall() {
        Map<String, Long> expected = Map.of("A", 20L, "C", 12L, "G", 17L, "T", 21L);
        Map<String, Long> actual = DnaNucleotidesCounter.count("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC");
        Assert.assertEquals(expected, actual);
    }

    @Test
    public void countLarge() {
        Map<String, Long> expected = Map.of("A", 222L, "C", 238L, "G", 245L, "T", 229L);
        Map<String, Long> actual = DnaNucleotidesCounter.count("AAGCGGACTACAGCTCTCAGTGATCTGGGCCTACATCAGCGGGCGCACACTTGGAAGCAATTAGTTGATCTTTACGAATGCATTGAGTTGACGTTTCGACTGCTATTATGTACGCGGTAGTCACTGGACTAGCCCGAGTTCAATGCGGGCCCTGCACCTGATCTTCCTGACAACCCCCTCTAGCTCCGTCGCTAATTTAGTCTAGGGCCGAGTCCGGTGTAAGTACGACACCTCCTGTTTCTGTTATGTCCGAGGTATCCGTACTTCAGTGGGCTGCAACTACTGAAAAACGCATAATCGGGGTAGATCGTAGGAGACAACTGCATGAAGATTTGGACTCGTTTGGAATGTCCGTCTTTGCATAGTAGTGAAGTGCAAATCAAACTGCCCGCGCTTGGTCCGGACCTAAAGGCAGGATCTGTGATAACGGCTCGCGCGTAGGCATATGTCTGTTTAATCCATACCGTCTGGTCCGCCATGATATGCTTAGGCGGTATTTACTGGGGGCCTGGACGTGACTACTTAAGTAGCGCCCCGGAACCGCGACCTGCCCCATAATAACCTTGGCTGGGACTCTGGGGTAGGACGCCGCGGCCTAGCATCGCAAGCGCTATCCTACAAGAGTCGGAAAGTAGCCGGCACTTCGTTACTTCCAGTGGGGGAAACCTTTCCGGGCTCCCTTACCGACGGCAGTGAGTACACGGCAGGTTCACATGAAAGCGGGTGTTTTCCCAGCAATTCAGCTGGGTAGTTCCACATCGCGTTATTCGCATGGAAATCAACGTGAATGTAGGTCCCACACAACATTCTAAAAGTGACACAAGCGTGGCAGAAGCGAATTAACTAGCTAGATCCCACCTATCGATTTCTGCACTGCCACTTAGATATATCATGACTGGATAGGGATTCCGACGTATGGTGCAGCGCAGAATCG");
        Assert.assertEquals(expected, actual);
    }
}
