//Dataset at the moment:
//TCATATTCTCTTCTCGTTCAGGGGTCAGGCGCGTGCGCAGGACACGATAGGGCAGTGGCTGTATTGACACGCCGGAATTATCTCTCAGTCGCGCGAGTACATGTGAAGTTGAAAGAATACCGGACAGTATGGCCGTGGAAAGTTAATTTTGTTTAAGGCTTTACTGCCTGCAATGACCTCCACTCGCAGTCTGGGCCCTACGTGAACCGAAGGAAGACTATGGGGTTACCCGCGAACTGAGTTTACTGAACTGCACGGTTTGTGGATAGGACTCTCGGGTCTAGTGGGCAAGTGAACCCCGCGCTGTGTACCGCCGTTGCAAGCAGTTTCGGTTATGTATGCGAGTATGGTGCCAGAGCCCTAGATATGGATCGGTCCACATCAGTTGAATCCCCGCCAGAGTACCACGCCGGCCAAGCTCGGGTCCAGCGGAGCGAAGCCCCAGACTCGGCCACGCCTGACCTATGGGCGGGTTTACTTGTTCCCATCGGTGGTTAGCCGCCGCCCGCCTAGAGTCAATCTTCACCGCGGTCGTAGATTACAGAGAGCCATTCTTGTAGATTTGGAGTCTGTCCACAGACTCGCTTGTAGCGCGTGATCGGCTACACTTTTTAACATATTCACTTTTCAAGGTTAGCTTAATACTAATAGGAAAATTTCTATCTGTATCTTGCATCCGAGAGGGAGTATTATCCGTGGTACGAGATTCCGTGGTTTGGAGAGATGAACAGCACAGTATGGGCACAGGTCCCGTTTCACAACACGTTTTCTACTCTGAACCCCTTGCCAAGCACGTATAACCTAACAATCCCTGGGCAACTCCTACGTTGTGAAAAAATATGGAACTGTGCCTTATCTGGAGCTTGCTTTCCAAATATTGCAGCGTCAGCAACGGAATGATTGATCGTAGCCCCGAGATT

package com.company;

public class Main {

    public static void main(String[] args) {

        //To load a dataset
        String s = "TCATATTCTCTTCTCGTTCAGGGGTCAGGCGCGTGCGCAGGACACGATAGGGCAGTGGCTGTATTGACACGCCGGAATTATCTCTCAGTCGCGCGAGTACATGTGAAGTTGAAAGAATACCGGACAGTATGGCCGTGGAAAGTTAATTTTGTTTAAGGCTTTACTGCCTGCAATGACCTCCACTCGCAGTCTGGGCCCTACGTGAACCGAAGGAAGACTATGGGGTTACCCGCGAACTGAGTTTACTGAACTGCACGGTTTGTGGATAGGACTCTCGGGTCTAGTGGGCAAGTGAACCCCGCGCTGTGTACCGCCGTTGCAAGCAGTTTCGGTTATGTATGCGAGTATGGTGCCAGAGCCCTAGATATGGATCGGTCCACATCAGTTGAATCCCCGCCAGAGTACCACGCCGGCCAAGCTCGGGTCCAGCGGAGCGAAGCCCCAGACTCGGCCACGCCTGACCTATGGGCGGGTTTACTTGTTCCCATCGGTGGTTAGCCGCCGCCCGCCTAGAGTCAATCTTCACCGCGGTCGTAGATTACAGAGAGCCATTCTTGTAGATTTGGAGTCTGTCCACAGACTCGCTTGTAGCGCGTGATCGGCTACACTTTTTAACATATTCACTTTTCAAGGTTAGCTTAATACTAATAGGAAAATTTCTATCTGTATCTTGCATCCGAGAGGGAGTATTATCCGTGGTACGAGATTCCGTGGTTTGGAGAGATGAACAGCACAGTATGGGCACAGGTCCCGTTTCACAACACGTTTTCTACTCTGAACCCCTTGCCAAGCACGTATAACCTAACAATCCCTGGGCAACTCCTACGTTGTGAAAAAATATGGAACTGTGCCTTATCTGGAGCTTGCTTTCCAAATATTGCAGCGTCAGCAACGGAATGATTGATCGTAGCCCCGAGATT";

        //To convert to char array
        char[] c = s.toCharArray();

        //To init frequency for A, C, G and T components
        int freq =0, freq2 = 0,freq3 = 0,freq4=0;

        //To realize the algorithm
        for(int i = 0; i < c.length; i++) {
            if(c[i]=='A') {
                c[i] = 'T';
                continue;
            }
            if(c[i]=='T') {
                c[i] = 'A';
                continue;
            }
            if(c[i]=='G') {
                c[i] = 'C';
                continue;
            }
            if(c[i]=='C') {
                c[i] = 'G';
                continue;
            }
        }

        //To set dataset-result
        for(int i = 0; i< c.length; i++) {
            System.out.print(c[c.length - i - 1]);
        }
    }
}

//The getting result
//AATCTCGGGGCTACGATCAATCATTCCGTTGCTGACGCTGCAATATTTGGAAAGCAAGCTCCAGATAAGGCACAGTTCCATATTTTTTCACAACGTAGGAGTTGCCCAGGGATTGTTAGGTTATACGTGCTTGGCAAGGGGTTCAGAGTAGAAAACGTGTTGTGAAACGGGACCTGTGCCCATACTGTGCTGTTCATCTCTCCAAACCACGGAATCTCGTACCACGGATAATACTCCCTCTCGGATGCAAGATACAGATAGAAATTTTCCTATTAGTATTAAGCTAACCTTGAAAAGTGAATATGTTAAAAAGTGTAGCCGATCACGCGCTACAAGCGAGTCTGTGGACAGACTCCAAATCTACAAGAATGGCTCTCTGTAATCTACGACCGCGGTGAAGATTGACTCTAGGCGGGCGGCGGCTAACCACCGATGGGAACAAGTAAACCCGCCCATAGGTCAGGCGTGGCCGAGTCTGGGGCTTCGCTCCGCTGGACCCGAGCTTGGCCGGCGTGGTACTCTGGCGGGGATTCAACTGATGTGGACCGATCCATATCTAGGGCTCTGGCACCATACTCGCATACATAACCGAAACTGCTTGCAACGGCGGTACACAGCGCGGGGTTCACTTGCCCACTAGACCCGAGAGTCCTATCCACAAACCGTGCAGTTCAGTAAACTCAGTTCGCGGGTAACCCCATAGTCTTCCTTCGGTTCACGTAGGGCCCAGACTGCGAGTGGAGGTCATTGCAGGCAGTAAAGCCTTAAACAAAATTAACTTTCCACGGCCATACTGTCCGGTATTCTTTCAACTTCACATGTACTCGCGCGACTGAGAGATAATTCCGGCGTGTCAATACAGCCACTGCCCTATCGTGTCCTGCGCACGCGCCTGACCCCTGAACGAGAAGAGAATATGA